### PR TITLE
fix:  github actions lint

### LINKED ISSUE #9: GitHub Actions Run failed: Go - master (3560551)
https://github.com/casbin/k8s-authz/runs/2855727369?check_suite_focus=true

image

### PR DESCRIPTION
**Pull request by ashish493**
@hsluoyz Sorry for the new PR, I was not able to remove the merge commit after constant trying. 
PR similar to -> #10 
I will add the tests in the next PR.

Fix: https://github.com/casbin/k8s-authz/issues/9

### CODE REVIEW

File: server.go [hunk 1]
```diff
@@ -59,27 +63,40 @@ func (gs *CasbinServerHandler) serve(w http.ResponseWriter, r *http.Request) {
 		glog.Errorf("Filed to load the policies: %v", err)
 		return
 	}
-	if e.HasPermissionForUser(user, operation_name) == true {
-		response := v1.AdmissionReview{
+	/*	if e.HasPermissionForUser(user, operation_name) == true {
+		aresponse := v1.AdmissionReview{
```
Comment (hsluoyz) [inline server.go]: aresponse?

File: server.go [hunk 2]
```diff
@@ -59,27 +63,40 @@ func (gs *CasbinServerHandler) serve(w http.ResponseWriter, r *http.Request) {
...
-				Message: " You are not authorized to perform any operations on these pods!",
-			},
-		},
+
+	if !e.HasPermissionForUser(user, operation_name) {
+		arReview.Response.Allowed = false
+		arReview.Response.Result = &metav1.Status{
+			Message: " You are not authorized to perform any operations on these pods!",
+		}
+		/*		aresponse := v1.AdmissionReview{
```
Comment (hsluoyz) [inline server.go]: aresponse?

**Review by hsluoyz — CHANGES_REQUESTED** [review]

File: server.go (hunk 1 above)
Comment (ashish493) [reply server.go]: aresponse is just an abbreviation for [Admission Response](https://pkg.go.dev/k8s.io/api/admission/v1#AdmissionResponse) which is used k8s [api](https://pkg.go.dev/k8s.io/api@v0.21.2/admission/v1) and since golang-lint doesn't allow underscore, I decided to keep it as aresponse.

File: server.go (hunk 2 above)
Comment (ashish493) [reply server.go]: Here I've just commented the part of old code for reference and the Response is the part of JSON object present in [Admission Review](https://github.com/kubernetes/api/blob/b71fde3beeb9f7eeb6b2f211fa27497ce9bbc397/admission/v1/types.go#L36) of k8s api.

File: server.go (hunk 1 above)
Comment (hsluoyz) [reply server.go]: What about just using `admissionResponse`? `aresponse` seems to be a typo to people like me.

File: server.go (hunk 2 above)
Comment (hsluoyz) [reply server.go]: What about just using `admissionResponse`? `aresponse` seems to be a typo to people like me.

File: server.go [hunk 3]
```diff
@@ -59,27 +63,40 @@ func (gs *CasbinServerHandler) serve(w http.ResponseWriter, r *http.Request) {
...
-	if e.HasPermissionForUser(user, operation_name) == true {
-		response := v1.AdmissionReview{
+	/*	if e.HasPermissionForUser(user, operation_name) == true {
+		aresponse := v1.AdmissionReview{
 			Response: &v1.AdmissionResponse{
 				Allowed: true,
 			},
 		}
+		return }
+	*/
```
Comment (hsluoyz) [inline server.go]: Are you commenting code manually? I recommend using shortcuts from IDEs like Goland or VSCode to comment lines. The manual commenting seems very ad-hoc to me.

image

**Review by hsluoyz — CHANGES_REQUESTED** [review]

File: server.go (hunk 3 above)
Comment (ashish493) [reply server.go]: Yeah I commented it manually. But No problem,I will keep that in mind. I am removing the comments now.

File: server.go (hunk 2 above)
Comment (ashish493) [reply server.go]: Sure.. I will make those changes. But after removing the comments, I think we don't need it then. Further if this term comes up I will be using admissionResponse

**Review by hsluoyz — APPROVED** [review]
